using PhantomDust.PcBridge.Core;
using Xunit;
namespace PhantomDust.PcBridge.Tests;
public class NearbyConnectionTests {
    private static BridgeStore Store()=>new(Path.Combine(Path.GetTempPath(),"pd-nearby-"+Guid.NewGuid(),"bridge.db"));
    private static NearbyConnectRequest Request(string? identity=null)=>new(Guid.NewGuid().ToString(),Convert.ToBase64String(System.Security.Cryptography.RandomNumberGenerator.GetBytes(32)),"Test phone",identity??Guid.NewGuid().ToString());
    [Fact] public void DiscoveryDoesNotGrantCredentialsBeforeLocalApproval(){using var s=Store();var r=Request();Assert.Equal("Pending",s.RequestNearbyConnection(r).State);Assert.Null(s.PollNearbyConnection(new(r.RequestId,r.Secret)).Pairing);Assert.Throws<BridgeException>(()=>s.PollNearbyConnection(new(r.RequestId,"wrong")));s.ApproveNearbyConnection(r.RequestId,true);var pair=s.PollNearbyConnection(new(r.RequestId,r.Secret)).Pairing!;Assert.Equal(pair.PairingId,s.Authenticate("Bearer "+pair.Token));Assert.Equal(pair,s.PollNearbyConnection(new(r.RequestId,r.Secret)).Pairing);Assert.Throws<BridgeException>(()=>s.ApproveNearbyConnection(r.RequestId,true));s.Revoke(pair.PairingId);Assert.Throws<BridgeException>(()=>s.PollNearbyConnection(new(r.RequestId,r.Secret)));}
    [Fact] public void RepairPreservesIdentityButPausesExistingDelivery(){using var s=Store();var identity=Guid.NewGuid().ToString();var first=s.Pair(new(s.BeginPairing("https://localhost","cert").BootstrapSecret,"Phone",identity));var request=Request(identity);s.RequestNearbyConnection(request);s.ApproveNearbyConnection(request.RequestId,true);Assert.Equal(first.PairingId,s.Authenticate("Bearer "+first.Token));var repaired=s.PollNearbyConnection(new(request.RequestId,request.Secret)).Pairing!;Assert.Equal(first.PairingId,repaired.PairingId);Assert.True(s.Paused(repaired.PairingId));Assert.Equal(first.PairingId,s.Authenticate("Bearer "+first.Token));s.FinishNearbyConnection(repaired.PairingId,"Bearer "+repaired.Token);Assert.Throws<BridgeException>(()=>s.Authenticate("Bearer "+first.Token));}
    [Fact] public void ReconnectInvitationIsDeviceBoundAndSingleUse(){using var s=Store();var a=s.Pair(new(s.BeginPairing("https://localhost","cert").BootstrapSecret,"A"));var b=s.Pair(new(s.BeginPairing("https://localhost","cert").BootstrapSecret,"B"));var id=s.RequestDeviceReconnect(a.PairingId);Assert.Null(s.PendingDeviceReconnect(b.PairingId));Assert.Throws<BridgeException>(()=>s.AnswerDeviceReconnect(b.PairingId,new(id,true)));s.AnswerDeviceReconnect(a.PairingId,new(id,true));Assert.Null(s.PendingDeviceReconnect(a.PairingId));Assert.Throws<BridgeException>(()=>s.AnswerDeviceReconnect(a.PairingId,new(id,true)));s.Revoke(a.PairingId);Assert.Throws<BridgeException>(()=>s.RequestDeviceReconnect(a.PairingId));}
    [Fact] public void RejectionNeverCreatesPairing(){using var s=Store();var r=Request();s.RequestNearbyConnection(r);s.ApproveNearbyConnection(r.RequestId,false);Assert.Equal("Rejected",s.PollNearbyConnection(new(r.RequestId,r.Secret)).State);Assert.Empty(s.HostDevices());}
    [Fact] public void RequestIdentityCannotChangeAndRequestsAreBounded(){using var s=Store();var r=Request();s.RequestNearbyConnection(r);Assert.Throws<BridgeException>(()=>s.RequestNearbyConnection(r with{DeviceName="Other"}));for(var i=0;i<7;i++)s.RequestNearbyConnection(Request());Assert.Throws<BridgeException>(()=>s.RequestNearbyConnection(Request()));}
    [Fact] public void UnpairAfterApprovalInvalidatesUnclaimedRepair(){using var s=Store();var identity=Guid.NewGuid().ToString();var first=s.Pair(new(s.BeginPairing("https://localhost","cert").BootstrapSecret,"Phone",identity));var request=Request(identity);s.RequestNearbyConnection(request);s.ApproveNearbyConnection(request.RequestId,true);s.Revoke(first.PairingId);Assert.Throws<BridgeException>(()=>s.PollNearbyConnection(new(request.RequestId,request.Secret)));}
    [Fact] public void AnotherAddressCanConnectWhenOnePeerHitsItsLimit(){using var s=Store();for(var i=0;i<8;i++)s.RequestNearbyConnection(Request(),"peer-one");Assert.Equal("Pending",s.RequestNearbyConnection(Request(),"peer-two").State);}
    [Fact] public void FirstPrimaryRequestFinishesLostHandoffAcknowledgement(){using var s=Store();var identity=Guid.NewGuid().ToString();var old=s.Pair(new(s.BeginPairing("https://localhost","cert").BootstrapSecret,"Phone",identity));var r=Request(identity);s.RequestNearbyConnection(r);s.ApproveNearbyConnection(r.RequestId,true);var next=s.PollNearbyConnection(new(r.RequestId,r.Secret)).Pairing!;Assert.Equal(old.PairingId,s.Authenticate("Bearer "+old.Token));Assert.Equal(next.PairingId,s.Authenticate("Bearer "+next.Token));Assert.Throws<BridgeException>(()=>s.Authenticate("Bearer "+old.Token));}
}
