using System.Text.Json;
using Microsoft.Data.Sqlite;
using PhantomDust.PcBridge.Core;
using Xunit;
namespace PhantomDust.PcBridge.Tests;
public class SyncTests {
    [Fact] public void LegacyMigrationKeepsCanonicalStateWhenLaunchContextChanges(){
        var root=Temp();var legacy=Path.Combine(root,"legacy");var canonical=Path.Combine(root,"canonical");Directory.CreateDirectory(Path.Combine(legacy,"live"));
        File.WriteAllText(Path.Combine(legacy,"live","marker.log"),"first");BridgePaths.MigrateLegacy(legacy,canonical);
        File.WriteAllText(Path.Combine(legacy,"live","marker.log"),"second");BridgePaths.MigrateLegacy(legacy,canonical);
        Assert.Equal("first",File.ReadAllText(Path.Combine(canonical,"live","marker.log")));
    }

    [Fact] public void CanonicalCertificateCannotBeReplacedByConflictingLegacyContext(){
        var root=Temp();var legacyA=Path.Combine(root,"a");var legacyB=Path.Combine(root,"b");var canonical=Path.Combine(root,"canonical");
        Directory.CreateDirectory(legacyA);Directory.CreateDirectory(legacyB);File.WriteAllText(Path.Combine(legacyA,"certificate.dpapi"),"A");File.WriteAllText(Path.Combine(legacyB,"certificate.dpapi"),"B");
        BridgePaths.MigrateLegacy(legacyA,canonical);BridgePaths.MigrateLegacy(legacyB,canonical);Assert.Equal("A",File.ReadAllText(Path.Combine(canonical,"certificate.dpapi")));
    }

    [Fact] public void ExistingCanonicalBundleBlocksLegacyDatabaseImport(){var root=Path.GetDirectoryName(Temp())!;var legacy=Path.Combine(root,"legacy");var canonical=Path.Combine(root,"canonical");Directory.CreateDirectory(canonical);File.WriteAllText(Path.Combine(canonical,"certificate.dpapi"),"canonical");using(var source=new BridgeStore(Path.Combine(legacy,"live","bridge.db"))){File.WriteAllText(Path.Combine(legacy,"certificate.dpapi"),"legacy");BridgePaths.MigrateLegacy(legacy,canonical);}Assert.False(File.Exists(Path.Combine(canonical,"live","bridge.db")));Assert.Equal("canonical",File.ReadAllText(Path.Combine(canonical,"certificate.dpapi")));}

    [Fact] public void LegacyWalDatabaseIsBackedUpAsPartOfMigration(){var root=Path.GetDirectoryName(Temp())!;var legacy=Path.Combine(root,"legacy");var canonical=Path.Combine(root,"canonical");var dbPath=Path.Combine(legacy,"live","bridge.db");string id;using(var source=new BridgeStore(dbPath)){id=source.BridgeId;File.WriteAllText(Path.Combine(legacy,"certificate.dpapi"),"identity");BridgePaths.MigrateLegacy(legacy,canonical);}using var migrated=new BridgeStore(Path.Combine(canonical,"live","bridge.db"));Assert.Equal(id,migrated.BridgeId);}

    [Fact] public void BridgeInstanceLockRejectsContention(){var root=Temp();using var first=BridgeInstanceLock.Acquire(root);Assert.Throws<InvalidOperationException>(()=>BridgeInstanceLock.Acquire(root));}
    [Fact] public void RequiredLegacySourceFailureLeavesCanonicalAbsent(){var root=Path.GetDirectoryName(Temp())!;var canonical=Path.Combine(root,"canonical");Assert.Throws<DirectoryNotFoundException>(()=>BridgePaths.MigrateLegacy(Path.Combine(root,"missing"),canonical,true));Assert.False(Directory.Exists(canonical));}
    [Fact] public void MigrationCommitCallbackFailureLeavesCanonicalAbsent(){var root=Path.GetDirectoryName(Temp())!;var legacy=Path.Combine(root,"legacy");var canonical=Path.Combine(root,"canonical");Directory.CreateDirectory(legacy);File.WriteAllText(Path.Combine(legacy,"marker.log"),"x");Assert.Throws<InvalidOperationException>(()=>BridgePaths.MigrateLegacy(legacy,canonical,false,()=>false));Assert.False(Directory.Exists(canonical));}
    [Fact] public void ActiveLiveMigrationPreservesConflictingInactiveDemoPairingForExplicitRepair(){var root=Path.GetDirectoryName(Temp())!;var legacy=Path.Combine(root,"legacy");var canonical=Path.Combine(root,"canonical");var liveDb=Path.Combine(legacy,"live","bridge.db");using(var live=new BridgeStore(liveDb)){Pair(live);File.WriteAllText(Path.Combine(legacy,"certificate.dpapi"),"A");File.WriteAllText(Path.Combine(legacy,"live","certificate.dpapi"),"A");using(var demo=new BridgeStore(Path.Combine(legacy,"demo","bridge.db"))){Pair(demo);File.WriteAllText(Path.Combine(legacy,"demo","certificate.dpapi"),"B");BridgePaths.MigrateLegacy(legacy,canonical,activeMode:"live");} }Assert.Equal("A",File.ReadAllText(Path.Combine(canonical,"certificate.dpapi")));Assert.True(File.Exists(Path.Combine(canonical,"migration-conflict-demo.txt")));Assert.Throws<InvalidOperationException>(()=>BridgePaths.EnsureModeIsUsable(canonical,"demo"));BridgePaths.EnsureModeIsUsable(canonical,"live");}

    [Fact] public void StatePreservesUnknownFieldsAndRejectsNewSchema(){
        var path=Temp();using(var store=new BridgeStore(path)){}
        using(var db=new SqliteConnection($"Data Source={path}")){db.Open();using var command=db.CreateCommand();command.CommandText="UPDATE state SET json=json_set(json, '$.futureFlag', json('true'), '$.schemaVersion', 999) WHERE id=1";command.ExecuteNonQuery();}
        Assert.Throws<InvalidOperationException>(()=>new BridgeStore(path));
        using(var db=new SqliteConnection($"Data Source={path}")){db.Open();using var command=db.CreateCommand();command.CommandText="UPDATE state SET json=json_set(json, '$.schemaVersion', 1) WHERE id=1";command.ExecuteNonQuery();}
        using(var store=new BridgeStore(path)){}
        using(var db=new SqliteConnection($"Data Source={path}")){db.Open();using var command=db.CreateCommand();command.CommandText="SELECT json FROM state WHERE id=1";var json=(string)command.ExecuteScalar()!;Assert.Equal(JsonValueKind.True,JsonDocument.Parse(json).RootElement.GetProperty("futureFlag").ValueKind);}
    }

    [Fact] public void CertificateIdentityIsIndependentOfModeAndExecutableDirectory(){
        var root=Path.Combine(Path.GetTempPath(),"bridge-identity",Guid.NewGuid().ToString());
        var live=Path.Combine(root,"live");var demo=Path.Combine(root,"demo");
        Assert.Equal(Path.Combine(root,"certificate.dpapi"),BridgeIdentityFiles.CertificatePath(root));
        Assert.Equal(BridgeIdentityFiles.CertificatePath(root),BridgeIdentityFiles.CertificatePath(root+Path.DirectorySeparatorChar));
        Assert.Equal(new[]{Path.Combine(live,"certificate.dpapi"),Path.Combine(demo,"certificate.dpapi")},BridgeIdentityFiles.LegacyCertificatePaths(root,live));
        Assert.Equal(BridgeIdentityFiles.CertificatePath(root),BridgeIdentityFiles.CertificatePath(Path.GetFullPath(root)));
    }

    [Fact] public void StoredBridgeIdentityRejectsSilentCertificateReplacement(){
        var path=Temp();var original=new string('A',64);var replacement=new string('B',64);
        using(var store=new BridgeStore(path)){Assert.True(store.CanCreateCertificate);store.ConfirmCertificateIdentity(original);Assert.False(store.CanCreateCertificate);store.ConfirmCertificateIdentity(original.ToLowerInvariant());}
        using(var store=new BridgeStore(path)){
            store.ConfirmCertificateIdentity(original);
            var error=Assert.Throws<InvalidOperationException>(()=>store.ConfirmCertificateIdentity(replacement));
            Assert.Contains("will not silently replace",error.Message);
        }
    }

    [Fact] public void PairingHistoryForbidsGeneratingAReplacementCertificate(){
        using var store=new BridgeStore(Temp());Assert.True(store.CanCreateCertificate);
        _=Pair(store);Assert.False(store.CanCreateCertificate);
    }

    [Fact] public void ExplicitAmendmentSupersedesInventoryBlockedPredecessor(){
        using var store=new BridgeStore(Temp());var pair=Pair(store);var original=Link(store,pair) with{ClientJourneyId=Guid.NewGuid().ToString()};
        var old=store.Queue(pair.PairingId,original);store.Reconcile(Snapshot(free:0),Planner);
        Assert.Equal(JobState.Blocked,Assert.Single(store.Jobs(pair.PairingId)).State);
        store.Queue(pair.PairingId,original with{ClientJourneyId=Guid.NewGuid().ToString(),SupersedesJourneyId=original.ClientJourneyId,Deck=original.Deck with{Revision=2}});
        Assert.Equal(JobState.Superseded,store.Jobs(pair.PairingId).Single(x=>x.JobId==old.JobId).State);
        Assert.Single(store.Jobs(pair.PairingId),x=>x.State==JobState.Queued);
    }
    [Fact] public void AmendmentBeforeOriginalArrivalTombstonesOriginal(){
        using var store=new BridgeStore(Temp());var pair=Pair(store);var original=Link(store,pair) with{ClientJourneyId=Guid.NewGuid().ToString()};
        var next=original with{ClientJourneyId=Guid.NewGuid().ToString(),SupersedesJourneyId=original.ClientJourneyId,Deck=original.Deck with{Revision=2}};
        var accepted=store.Queue(pair.PairingId,next);Assert.Equal(JobState.Queued,accepted.State);
        Assert.Throws<BridgeException>(()=>store.Queue(pair.PairingId,original));Assert.Single(store.Jobs(pair.PairingId));
    }
    [Fact] public void OlderSnapshotWithoutProfileImportCapabilityDefaultsToUnsupported(){
        var snapshot=System.Text.Json.JsonSerializer.Deserialize<Snapshot>("{\"profileKey\":\"p\",\"capturedAt\":1,\"gameRunning\":true,\"profileVerified\":true,\"inventoryVerified\":false,\"writeSupported\":false,\"safeStateVerified\":false,\"arsenals\":[],\"freeInventory\":{} }",Wire.Json)!;
        Assert.False(snapshot.ProfileImportSupported);
    }

    [Fact] public void SharedProtocolFixture(){using var f=System.Text.Json.JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"fixtures","reclaim-plan.json")));var request=f.RootElement.GetProperty("request").Deserialize<PlanRequest>(Wire.Json)!;var snapshot=f.RootElement.GetProperty("snapshot").Deserialize<Snapshot>(Wire.Json)!;var result=Planner.Plan(request,snapshot);Assert.True(result.CanBuild);Assert.False(result.CanApply);Assert.Equal(0,result.NewFreeInventory["001"]);Assert.Empty(result.MissingSkills);}
    static readonly CatalogueSkill[] Skills=[new("000","Aura",null,"aura"),new("001","Wave","psycho","attack"),new("002","Other","nature","attack")];
    static Planner Planner=>new(Skills);
    static DeckSpec Deck(int copies=3)=>new(Guid.NewGuid().ToString(),1,"PhoneName",Enumerable.Repeat("001",copies).Concat(Enumerable.Repeat("000",30-copies)).ToArray(),2,"retail_2017_full");
    static Snapshot Snapshot(int free=1,int targetCopies=2)=>new("p","snapshot",Wire.Now,true,true,true,false,true,[new(1,"PC name",2,Enumerable.Repeat("001",targetCopies).Concat(Enumerable.Repeat("000",30-targetCopies)).ToArray(),"target"),new(2,"Unrelated",2,Enumerable.Repeat("002",3).Concat(Enumerable.Repeat("000",27)).ToArray(),"other")],new Dictionary<string,int>{{"001",free},{"002",0}});
    static PlanResult Plan(DeckSpec? deck=null,Snapshot? snapshot=null,string? expected="target")=>Planner.Plan(new("p",1,expected,deck??Deck()),snapshot??Snapshot());
    [Fact] public void ReclaimsTargetAndPreservesOwnership(){var p=Plan();Assert.True(p.CanBuild);Assert.False(p.CanApply);Assert.Equal(0,p.NewFreeInventory["001"]);Assert.Empty(p.MissingSkills);Assert.Equal("target",p.TargetFingerprint);}
    [Fact] public void MissingOne(){var p=Plan(snapshot:Snapshot(0));Assert.False(p.CanBuild);Assert.Equal(new MissingSkill("001",3,2,1),Assert.Single(p.MissingSkills));}
    [Fact] public void AuraUnlimited(){Assert.True(Plan(Deck(0),Snapshot(0,0)).CanBuild);}
    [Fact] public void FourCopiesRejected(){Assert.Contains(Plan(Deck(4)).Blockers,b=>b.Code=="CopyLimit");}
    [Fact] public void AllShortagesWithoutReclaimingOtherArsenal(){var d=Deck() with{SkillIds=new[]{"001","001","001","002"}.Concat(Enumerable.Repeat("000",26)).ToArray()};var p=Plan(d,Snapshot(0));Assert.Equal(2,p.MissingSkills.Count);Assert.Equal(0,p.MissingSkills.Single(x=>x.SkillId=="002").Available);}
    [Fact] public void WrongCase(){Assert.Contains(Plan(Deck() with{CaseCapacity=3}).Blockers,b=>b.Code=="CaseMismatch");}
    [Fact] public void SchoolsRespectChosenCase(){var d=Deck() with{CaseCapacity=1,SkillIds=new[]{"001","002"}.Concat(Enumerable.Repeat("000",28)).ToArray()};Assert.Contains(Plan(d).Blockers,b=>b.Code=="SchoolLimit");}
    [Fact] public void UnknownModdedRejected(){var d=Deck() with{SkillIds=Enumerable.Repeat("AAAA",30).ToArray()};Assert.Contains(Plan(d).Blockers,b=>b.Code=="UnknownSkill");}
    [Fact] public void TargetConflict(){Assert.Contains(Plan(expected:"old").Blockers,b=>b.Code=="ConflictPcChanged");}
    [Fact] public void UnknownInventoryDoesNotInventShortages(){var p=Plan(snapshot:Snapshot() with{InventoryVerified=false});Assert.True(p.CanBuild);Assert.Empty(p.MissingSkills);Assert.Empty(p.NewFreeInventory);}
    [Fact] public void InvalidCountsBlocked(){Assert.Contains(Plan(snapshot:Snapshot(-1)).Blockers,b=>b.Code=="InventoryInvalid");}
    [Fact] public void ProfileMismatch(){Assert.Contains(Plan(snapshot:Snapshot() with{ProfileKey="other"}).Blockers,b=>b.Code=="ProfileMismatch");}
    [Fact] public void MissingTarget(){Assert.Contains(Plan(snapshot:Snapshot() with{Arsenals=[]}).Blockers,b=>b.Code=="NoTarget");}
    [Fact] public void GameClosedAndUnsafeNeverApply(){Assert.False(Plan(snapshot:Snapshot() with{GameRunning=false,SafeStateVerified=false}).CanApply);Assert.False(new DisabledProfileWriter().WriteSupported);}
    [Fact] public void RulesetAndSlots(){var p=Plan(Deck() with{RulesetId="mod",SkillIds=[]});Assert.Contains(p.Blockers,b=>b.Code=="UnsupportedRuleset");Assert.Contains(p.Blockers,b=>b.Code=="SlotCount");}
    [Theory][InlineData("")][InlineData("               ")][InlineData("SixteenCharsHere")][InlineData("Has-Dash")][InlineData("Café")][InlineData("!!!")]
    public void InvalidArsenalNamesAreBlockedByPlanning(string name){Assert.Contains(Plan(Deck() with{Name=name}).Blockers,b=>b.Code=="InvalidName");}
    [Theory][InlineData("U Turn")][InlineData("A B C D E F G H")]
    public void SpacedArsenalNamesAreAcceptedByPlanning(string name){Assert.DoesNotContain(Plan(Deck() with{Name=name}).Blockers,b=>b.Code=="InvalidName");}
    static PairResponse Pair(BridgeStore s){var p=s.BeginPairing("https://localhost:17431","cert");return s.Pair(new(p.BootstrapSecret,"phone"));}
    static QueueRequest Link(BridgeStore s,PairResponse pair){var d=Deck();var l=new LinkRequest(Guid.NewGuid().ToString(),d.DeckId,"p",1,1,"target");s.Link(pair.PairingId,l,Snapshot(targetCopies:0));return new("p",1,"target",d,"target",l.LinkId,1);}
    static string Temp()=>Path.Combine(Path.GetTempPath(),"pd-bridge-tests",Guid.NewGuid().ToString(),"bridge.db");
    [Theory] [InlineData(1,1,true)] [InlineData(1,2,true)] [InlineData(1,3,true)] [InlineData(2,1,false)] [InlineData(2,2,true)] [InlineData(2,3,true)] [InlineData(3,1,false)] [InlineData(3,2,false)] [InlineData(3,3,true)]
    public void CompatibleCasesAllowLargerCapacity(int phoneCase,int pcCase,bool allowed){var s=Snapshot();s=s with{Arsenals=s.Arsenals.Select(x=>x.Slot==1?x with{CaseCapacity=pcCase}:x).ToArray()};var p=Plan(Deck() with{CaseCapacity=phoneCase},s);Assert.Equal(allowed,!p.Blockers.Any(x=>x.Code=="CaseMismatch"));Assert.Equal(pcCase,s.Arsenals[0].CaseCapacity);}
    [Fact] public void OccupiedCaseRequiresExplicitFingerprintBoundOverwrite(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=new LinkRequest(Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),"p",1,1,"target",true);Assert.Throws<BridgeException>(()=>s.Link(p.PairingId,r with{ConfirmedFingerprint="stale"},Snapshot()));Assert.True(s.Link(p.PairingId,r,Snapshot()).Active);}
    [Fact] public void IdenticalClaimDoesNotGrantOverwriteAndStillChecksOwnership(){
        using var store=new BridgeStore(Temp());var owner=Pair(store);var snapshot=Snapshot();var target=snapshot.Arsenals[0];
        var proof=new DeckSpec(Guid.NewGuid().ToString(),1,target.Name,target.SkillIds.Reverse().ToArray(),target.CaseCapacity,"retail_2017_full");
        var request=new LinkRequest(Guid.NewGuid().ToString(),proof.DeckId,"p",target.Slot,1,target.Fingerprint!,IdenticalDeck:proof);
        Assert.Throws<BridgeException>(()=>store.Link(owner.PairingId,request with{IdenticalDeck=proof with{Name="Different"}},snapshot));
        Assert.True(store.Link(owner.PairingId,request,snapshot).Active);
        var other=Pair(store);Assert.Throws<BridgeException>(()=>store.Link(other.PairingId,request with{LinkId=Guid.NewGuid().ToString()},snapshot));
        Assert.Throws<BridgeException>(()=>store.Link(owner.PairingId,request with{ConfirmedFingerprint="stale"},snapshot));
        Assert.Empty(store.Jobs(owner.PairingId));
    }
    [Fact] public void ContentHashIgnoresOrderButCountsAuraAndCopies(){
        string[] cards=["001","002",..Enumerable.Repeat("000",28)];
        Assert.Equal(Planner.CardContentFingerprint(cards),Planner.CardContentFingerprint(cards.Reverse()));
        Assert.NotEqual(Planner.CardContentFingerprint(cards),Planner.CardContentFingerprint(cards.Skip(1)));
        Assert.StartsWith("v2:",Planner.CardContentFingerprint(cards));
    }
    [Fact] public void FirstLinkRejectsOccupiedCase(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=new LinkRequest(Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),"p",1,1,"target");Assert.Throws<BridgeException>(()=>s.Link(p.PairingId,r,Snapshot()));s.Link(p.PairingId,r,Snapshot(targetCopies:0));Assert.Throws<BridgeException>(()=>s.Link(p.PairingId,r with{LinkGeneration=2},Snapshot()));}
    [Fact] public void EmptyCasePreviewBlocksAndReportsShortages(){var result=Planner.Plan(new("p",1,"target",Deck(),true),Snapshot(free:0));Assert.False(result.CanBuild);Assert.Contains(result.Blockers,x=>x.Code=="EmptyCaseRequired");Assert.Equal(1,Assert.Single(result.MissingSkills).Missing);}
    [Fact] public void PairingRequiresSecretAndIsSingleUse(){using var s=new BridgeStore(Temp());var p=s.BeginPairing("https://localhost","cert");Assert.Throws<BridgeException>(()=>s.Pair(new("bad","phone")));var pair=s.Pair(new(p.BootstrapSecret,"phone"));Assert.Equal(pair.PairingId,s.Authenticate("Bearer "+pair.Token));Assert.Throws<BridgeException>(()=>s.Pair(new(p.BootstrapSecret,"phone")));s.Revoke(pair.PairingId);Assert.Throws<BridgeException>(()=>s.Authenticate("Bearer "+pair.Token));}
    [Fact] public void PairingSameVerifiedPhoneIdentityRotatesTokenAndKeepsOwnership(){using var s=new BridgeStore(Temp());var firstPayload=s.BeginPairing("https://localhost","cert");var first=s.Pair(new(firstPayload.BootstrapSecret,"Oppo","stable-phone"));var request=Link(s,first);var secondPayload=s.BeginPairing("https://localhost","cert");var second=s.Pair(new(secondPayload.BootstrapSecret,"Oppo restored","stable-phone"));Assert.Equal(first.PairingId,second.PairingId);Assert.Throws<BridgeException>(()=>s.Authenticate("Bearer "+first.Token));Assert.Equal(first.PairingId,s.Authenticate("Bearer "+second.Token));Assert.Equal(first.PairingId,Assert.Single(s.Links(first.PairingId)).PairingId);}
    [Fact] public void QueueSurvivesRestartAndRetriesAreIdempotent(){var path=Temp();PairResponse pair;QueueRequest r;string id;string bridge;using(var s=new BridgeStore(path)){pair=Pair(s);r=Link(s,pair);id=s.Queue(pair.PairingId,r).JobId;bridge=s.BridgeId;Assert.Equal(id,s.Queue(pair.PairingId,r).JobId);}using(var s=new BridgeStore(path)){Assert.Equal(bridge,s.BridgeId);Assert.Equal(pair.PairingId,s.Authenticate("Bearer "+pair.Token));Assert.Equal(r.Deck.DeckId,Assert.Single(s.Jobs(pair.PairingId)).DeckId);Assert.Equal(id,s.Queue(pair.PairingId,r).JobId);}}
    [Fact] public void ProfileImportClaimsEveryTargetAtomicallyAndIsIdempotent(){using var store=new BridgeStore(Temp());var pair=Pair(store);var raw=Snapshot();var decks=raw.Arsenals.Select(x=>x with{ContentFingerprint=Planner.CardContentFingerprint(x.SkillIds)}).ToArray();var snapshot=raw with{Arsenals=decks,GameProfileSlot=1,GameProfileDisplayName="final"};var request=new ProfileImportRequest(Guid.NewGuid().ToString(),"p",decks.Select(x=>new ProfileImportDeck(Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),x.Slot,x.Fingerprint!,x.ContentFingerprint!)).ToArray());var first=store.ImportProfile(pair.PairingId,request,snapshot);Assert.Equal(2,first.Links.Count);Assert.All(first.Links,x=>Assert.True(x.Active));var retry=store.ImportProfile(pair.PairingId,request,snapshot);Assert.True(retry.AlreadyApplied);Assert.Equal(first.Links,retry.Links);var changed=request with{ImportId=Guid.NewGuid().ToString(),Decks=request.Decks.Skip(1).ToArray()};Assert.Throws<BridgeException>(()=>store.ImportProfile(pair.PairingId,changed,snapshot));Assert.Equal(2,store.Links(pair.PairingId).Length);}
    [Fact] public void RevisionSupersessionAndPayloadMismatch(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var j=s.Queue(p.PairingId,r);Assert.Throws<BridgeException>(()=>s.Queue(p.PairingId,r with{Deck=r.Deck with{Name="renamed locally"}}));Assert.Throws<BridgeException>(()=>s.Queue(p.PairingId,r with{Deck=r.Deck with{CaseCapacity=3}}));s.Queue(p.PairingId,r with{Deck=r.Deck with{Revision=2}});Assert.Contains(s.Jobs(p.PairingId),x=>x.State==JobState.Superseded);Assert.Equal(2,s.Jobs(p.PairingId).Length);}
    [Fact] public void OwnershipAndUnlinkCancel(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var j=s.Queue(p.PairingId,r);var other=Pair(s);Assert.Empty(s.Jobs(other.PairingId));Assert.Throws<BridgeException>(()=>s.Cancel(other.PairingId,j.JobId));Assert.Throws<BridgeException>(()=>s.Link(other.PairingId,new(Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),"p",1,1,"target"),Snapshot()));s.Unlink(p.PairingId,r.LinkId);Assert.Equal(JobState.Cancelled,Assert.Single(s.Jobs(p.PairingId)).State);Assert.Throws<BridgeException>(()=>s.Queue(p.PairingId,r));}
    [Fact] public void LinkRenewalDoesNotRestampCancelledJobsAndSupersedesActiveGeneration(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var cancelled=s.Queue(p.PairingId,r);s.Cancel(p.PairingId,cancelled.JobId);var cancelledAt=Assert.Single(s.Jobs(p.PairingId),x=>x.JobId==cancelled.JobId).UpdatedAt;var active=s.Queue(p.PairingId,r with{Deck=r.Deck with{Revision=2},ClientJourneyId=Guid.NewGuid().ToString()});var renewed=s.Link(p.PairingId,new(r.LinkId,r.Deck.DeckId,r.ProfileKey,r.TargetSlot,2,r.ConfirmedFingerprint),Snapshot(targetCopies:0));var jobs=s.Jobs(p.PairingId);Assert.Equal(cancelledAt,jobs.Single(x=>x.JobId==cancelled.JobId).UpdatedAt);Assert.Equal(JobState.Cancelled,jobs.Single(x=>x.JobId==cancelled.JobId).State);Assert.Equal(JobState.Superseded,jobs.Single(x=>x.JobId==active.JobId).State);Assert.Equal("Replaced by a renewed PC link.",jobs.Single(x=>x.JobId==active.JobId).Reason);}
    [Fact] public void ExplicitCancelUsesUserInitiatedCopy(){using var s=new BridgeStore(Temp());var p=Pair(s);var j=s.Queue(p.PairingId,Link(s,p));var cancelled=s.Cancel(p.PairingId,j.JobId);Assert.True((bool)cancelled.GetType().GetProperty("cancelled")!.GetValue(cancelled)!);Assert.Equal("Cancelled by you before the PC arsenal was updated.",cancelled.GetType().GetProperty("reason")!.GetValue(cancelled));Assert.Equal("Cancelled by you before the PC arsenal was updated.",Assert.Single(s.Jobs(p.PairingId)).Reason);}
    [Fact] public void QueueWaitsGameThenBlocksWrites(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);s.Queue(p.PairingId,r);s.Reconcile(Snapshot() with{GameRunning=false},Planner);Assert.Equal(JobState.WaitingForGame,Assert.Single(s.Jobs(p.PairingId)).State);s.Reconcile(Snapshot(),Planner);Assert.Equal(JobState.Blocked,Assert.Single(s.Jobs(p.PairingId)).State);Assert.True(Assert.Single(s.Jobs(p.PairingId)).Plan!.CanBuild);}
    [Fact] public void WrongGameProfileWaitsWithoutDiscardingJob(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);s.Reconcile(Snapshot() with{ProfileKey="other-profile"},Planner);var job=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(queued.JobId,job.JobId);Assert.Equal(JobState.Blocked,job.State);Assert.Contains(job.Plan!.Blockers,x=>x.Code=="ProfileMismatch");s.Reconcile(Snapshot(),Planner);Assert.Equal(queued.JobId,Assert.Single(s.Jobs(p.PairingId)).JobId);}
    [Fact] public void RenamedBoundProfileRequiresExplicitRebind(){using var s=new BridgeStore(Temp());var p=Pair(s);var d=Deck();var request=new LinkRequest(Guid.NewGuid().ToString(),d.DeckId,"p",1,1,"target");var linkedSnapshot=Snapshot(targetCopies:0) with{GameProfileDisplayName="PlayerOne"};s.Link(p.PairingId,request,linkedSnapshot);s.Queue(p.PairingId,new("p",1,"target",d,"target",request.LinkId,1));s.Reconcile(Snapshot() with{GameProfileDisplayName="Renamed"},Planner);var job=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(JobState.Blocked,job.State);Assert.Contains(job.Plan!.Blockers,x=>x.Code=="ProfileBindingChanged");}
    [Fact] public void PausePersistsAndStopsReconciliation(){using var s=new BridgeStore(Temp());var p=Pair(s);s.Queue(p.PairingId,Link(s,p));s.Pause(p.PairingId,true);s.Reconcile(Snapshot(),Planner);Assert.Equal(JobState.Queued,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void JobWaitingNoticesAreNormalizedDeduplicatedAndDurable(){
        var path=Temp();string pairing;
        using(var s=new BridgeStore(path)){
            var p=Pair(s);pairing=p.PairingId;s.Queue(pairing,Link(s,p));s.Reconcile(Snapshot() with{GameRunning=false},Planner);
            s.RecordJobNotices();var waiting=Assert.Single(s.ClaimNotices());Assert.Contains("WaitingForGame",waiting.Id);Assert.Contains("Waiting for Phantom Dust",waiting.Message);
            s.RecordJobNotices();Assert.Empty(s.ClaimNotices());
            s.ExecuteOneNormalJob(new FixedReader(Snapshot() with{WriteSupported=true,GameForeground=false}),Planner,(_,_)=>new(JobState.Completed));
            s.RecordJobNotices();var readiness=Assert.Single(s.ClaimNotices());Assert.Contains("WaitingForReadiness",readiness.Id);
            s.RecordJobNotices();Assert.Empty(s.ClaimNotices());
        }
        using(var restarted=new BridgeStore(path)){restarted.RecordJobNotices();Assert.Empty(restarted.ClaimNotices());Assert.Single(restarted.Jobs(pairing));}
    }
    [Fact] public void JobBlockedRecoveryAndCompletionNoticesUseOneStableMilestoneEach(){
        using(var blocked=new BridgeStore(Temp())){var p=Pair(blocked);blocked.Queue(p.PairingId,Link(blocked,p));blocked.Reconcile(Snapshot(free:0),Planner);blocked.RecordJobNotices();var notice=Assert.Single(blocked.ClaimNotices());Assert.Contains("Blocked",notice.Id);blocked.RecordJobNotices();Assert.Empty(blocked.ClaimNotices());}
        using(var recovery=new BridgeStore(Temp())){var p=Pair(recovery);recovery.Queue(p.PairingId,Link(recovery,p));recovery.ExecuteOneNormalJob(new FixedReader(Snapshot() with{WriteSupported=true}),Planner,(_,_)=>new(JobState.RecoveryRequired,Reason:"Save could not be confirmed."));recovery.RecordJobNotices();var notice=Assert.Single(recovery.ClaimNotices());Assert.Contains("RecoveryRequired",notice.Id);Assert.Contains("Save could not be confirmed",notice.Message);recovery.RecordJobNotices();Assert.Empty(recovery.ClaimNotices());}
        using(var completed=new BridgeStore(Temp())){var p=Pair(completed);var job=completed.Queue(p.PairingId,Link(completed,p));completed.ExecuteOneNormalJob(new FixedReader(Snapshot() with{WriteSupported=true}),Planner,(_,_)=>new(JobState.Completed));completed.RecordJobNotices();var notice=Assert.Single(completed.ClaimNotices());Assert.Equal($"job:{job.JobId}",notice.Id);completed.RecordJobNotices();Assert.Empty(completed.ClaimNotices());}
    }
    [Fact] public void MappingIsCompleteAndNonNumeric(){var m=new SkillIdMap(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"skill-id-map.json")));Assert.Equal(new byte[]{5,0},m.Encode("004"));Assert.Equal("005",m.Decode(4,0));foreach(var id in Enumerable.Range(0,375).Select(x=>x.ToString("D3"))){var b=m.Encode(id);Assert.Equal(id,m.Decode(b[0],b[1]));}Assert.Throws<InvalidDataException>(()=>m.Decode(0xAA,0xAA));}
    [Fact] public void OlderRevisionRejectedAcrossLinkGenerations(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);s.Queue(p.PairingId,r with{Deck=r.Deck with{Revision=10}});s.Link(p.PairingId,new(r.LinkId,r.Deck.DeckId,r.ProfileKey,1,2,"target"),Snapshot(targetCopies:0));Assert.Throws<BridgeException>(()=>s.Queue(p.PairingId,r with{LinkGeneration=2}));}
    [Fact] public void CancelledRetryRequiresNewConfirmation(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var j=s.Queue(p.PairingId,r);s.Cancel(p.PairingId,j.JobId);Assert.Throws<BridgeException>(()=>s.Queue(p.PairingId,r));s.Link(p.PairingId,new(r.LinkId,r.Deck.DeckId,r.ProfileKey,1,2,"target"),Snapshot(targetCopies:0));Assert.Equal(JobState.Queued,s.Queue(p.PairingId,r with{LinkGeneration=2}).State);}
    [Fact] public void NormalFocusWaitNeverResumesIntoControlledTestSession(){
        using var store=new BridgeStore(Temp());var pair=Pair(store);store.Queue(pair.PairingId,Link(store,pair));
        var snapshot=Snapshot() with{WriteSupported=true,GameForeground=false};var writes=0;
        store.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>true);
        store.ExecuteOneNormalJob(new FixedReader(snapshot with{GameForeground=true,ControlledTestSession=true}),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>true);
        Assert.Equal(0,writes);Assert.Equal(JobState.WaitingForGameReady,Assert.Single(store.Jobs(pair.PairingId)).State);
    }
    [Fact] public void InitialFocusWaitAutomaticallyResumesWithoutPretendingAWriteOccurred(){
        using var store=new BridgeStore(Temp());var pair=Pair(store);store.Queue(pair.PairingId,Link(store,pair));
        var snapshot=Snapshot() with{WriteSupported=true,GameForeground=false};var writes=0;var probes=0;
        for(var i=0;i<2;i++)store.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>{probes++;return true;});
        Assert.Equal(0,writes);Assert.Equal(0,probes);Assert.Equal("WaitingForGame",Assert.Single(store.Jobs(pair.PairingId)).Phase);
        store.ExecuteOneNormalJob(new FixedReader(snapshot with{GameForeground=true}),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>true);
        Assert.Equal(1,writes);Assert.Equal(JobState.Completed,Assert.Single(store.Jobs(pair.PairingId)).State);
    }
    [Fact] public void BackgroundSnapshotWaitsForFocusBeforeWriterAttempt(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true,GameForeground=false};var writes=0;s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>{writes++;return new(JobState.Completed);});var waiting=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(queued.JobId,waiting.JobId);Assert.Equal(JobState.WaitingForGameReady,waiting.State);Assert.Contains("Focus Phantom Dust",waiting.Reason);Assert.Equal(0,writes);}
    [Fact] public void WaitingForFramesIsNotReclaimedAndRetryRunsExactlyOnce(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true,GameForeground=true};var writes=0;s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>{writes++;return new(JobState.WaitingForFrames,Reason:"Phantom Dust is paused or minimized.");});Assert.Equal(JobState.WaitingForFrames,Assert.Single(s.Jobs(p.PairingId)).State);s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>{writes++;return new(JobState.Completed);});Assert.Equal(1,writes);var retried=s.Retry(p.PairingId,queued.JobId);Assert.Equal(queued.JobId,retried.JobId);Assert.Equal(JobState.Queued,retried.State);s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>true);Assert.Equal(2,writes);Assert.Equal(JobState.Completed,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void BackgroundWaitDoesNotWriteUntilARealFrameIsObserved(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true,GameForeground=true};var writes=0;s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>{writes++;return new(JobState.WaitingForFrames);});var waiting=s.WaitForGame(p.PairingId,queued.JobId);Assert.Equal(JobState.WaitingForGameReady,waiting.State);s.ExecuteOneNormalJob(new FixedReader(snapshot with{GameForeground=false}),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>false);Assert.Equal(1,writes);Assert.Equal(JobState.WaitingForGameReady,Assert.Single(s.Jobs(p.PairingId)).State);s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>true);Assert.Equal(2,writes);Assert.Equal(JobState.Completed,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void BackgroundWaitRevalidatesTargetBeforeResuming(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true};var writes=0;s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>{writes++;return new(JobState.WaitingForFrames);});s.WaitForGame(p.PairingId,queued.JobId);var changed=snapshot with{Arsenals=snapshot.Arsenals.Select(x=>x.Slot==1?x with{Fingerprint="changed"}:x).ToArray()};s.ExecuteOneNormalJob(new FixedReader(changed),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>true);var blocked=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(1,writes);Assert.Equal(JobState.Blocked,blocked.State);Assert.Contains(blocked.Plan!.Blockers,x=>x.Code=="ConflictPcChanged");}
    [Fact] public void BackgroundWaitIsOwnedIdempotentAndCancellable(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true};s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>new(JobState.WaitingForFrames));var other=Pair(s);Assert.Throws<BridgeException>(()=>s.WaitForGame(other.PairingId,queued.JobId));Assert.Equal(queued.JobId,s.WaitForGame(p.PairingId,queued.JobId).JobId);Assert.Equal(JobState.WaitingForGameReady,s.WaitForGame(p.PairingId,queued.JobId).State);s.Cancel(p.PairingId,queued.JobId);Assert.Equal(JobState.Cancelled,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void BackgroundWaitSurvivesBridgeRestart(){var path=Temp();PairResponse pair;QueueRequest request;string jobId;var snapshot=Snapshot() with{WriteSupported=true};using(var first=new BridgeStore(path)){pair=Pair(first);request=Link(first,pair);jobId=first.Queue(pair.PairingId,request).JobId;first.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>new(JobState.WaitingForFrames));first.WaitForGame(pair.PairingId,jobId);}using var restarted=new BridgeStore(path);var waiting=Assert.Single(restarted.Jobs(pair.PairingId));Assert.Equal(jobId,waiting.JobId);Assert.Equal(JobState.WaitingForGameReady,waiting.State);var writes=0;restarted.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_,_)=>{writes++;return new(JobState.Completed);},()=>false);Assert.Equal(0,writes);Assert.Equal(JobState.WaitingForGameReady,Assert.Single(restarted.Jobs(pair.PairingId)).State);}
    [Fact] public void WaitingForFramesRetryChecksOwnerStateAndStaleContext(){using var s=new BridgeStore(Temp());var owner=Pair(s);var r=Link(s,owner);var queued=s.Queue(owner.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true};s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>new(JobState.WaitingForFrames));var other=Pair(s);Assert.Throws<BridgeException>(()=>s.Retry(other.PairingId,queued.JobId));Assert.Throws<BridgeException>(()=>s.Retry(owner.PairingId,"missing"));s.Link(owner.PairingId,new(r.LinkId,r.Deck.DeckId,r.ProfileKey,1,2,"target"),Snapshot(targetCopies:0));Assert.Throws<BridgeException>(()=>s.Retry(owner.PairingId,queued.JobId));}
    [Fact] public void RetryRejectsQueuedAndWaitingForFramesCanCancel(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);Assert.Throws<BridgeException>(()=>s.Retry(p.PairingId,queued.JobId));var snapshot=Snapshot() with{WriteSupported=true};s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>new(JobState.WaitingForFrames));s.Cancel(p.PairingId,queued.JobId);Assert.Equal(JobState.Cancelled,s.Jobs(p.PairingId).Single().State);}
    [Fact] public void NewerQueueSupersedesWaitingForFrames(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var old=s.Queue(p.PairingId,r);var snapshot=Snapshot() with{WriteSupported=true};s.ExecuteOneNormalJob(new FixedReader(snapshot),Planner,(_,_)=>new(JobState.WaitingForFrames));var next=s.Queue(p.PairingId,r with{Deck=r.Deck with{Revision=2},ClientJourneyId=Guid.NewGuid().ToString()});Assert.Equal(JobState.Superseded,s.Jobs(p.PairingId).Single(x=>x.JobId==old.JobId).State);Assert.Equal(JobState.Queued,next.State);}
    [Fact] public void ReviewedOwnershipTransferIsAtomicAndRejectsApplyingOwner(){using var s=new BridgeStore(Temp());var p=Pair(s);var old=Link(s,p);var queued=s.Queue(p.PairingId,old);var replacement=new LinkRequest(Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),old.ProfileKey,old.TargetSlot,1,old.ConfirmedFingerprint,ReplacesLinkId:old.LinkId,ReplacesLinkGeneration:old.LinkGeneration);var next=s.Link(p.PairingId,replacement,Snapshot(targetCopies:0));Assert.True(next.Active);Assert.DoesNotContain(s.Links(p.PairingId),x=>x.LinkId==old.LinkId&&x.Active);Assert.Equal(JobState.Superseded,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void ReviewedSameDeckLinkDriftReplacesOldLink(){using var s=new BridgeStore(Temp());var p=Pair(s);var old=Link(s,p);var queued=s.Queue(p.PairingId,old);var replacement=new LinkRequest(Guid.NewGuid().ToString(),old.Deck.DeckId,old.ProfileKey,old.TargetSlot,1,old.ConfirmedFingerprint,ReplacesLinkId:old.LinkId,ReplacesLinkGeneration:old.LinkGeneration);var next=s.Link(p.PairingId,replacement,Snapshot(targetCopies:0));Assert.True(next.Active);Assert.DoesNotContain(s.Links(p.PairingId),x=>x.LinkId==old.LinkId&&x.Active);Assert.Equal(replacement.LinkId,Assert.Single(s.Links(p.PairingId)).LinkId);Assert.Equal(JobState.Superseded,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void QueueAmendmentCarriesImmutableSourceAndRejectsApplyingJourney(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var source=Guid.NewGuid().ToString();var old=s.Queue(p.PairingId,r with{ClientJourneyId=source});var amended=s.Queue(p.PairingId,r with{Deck=r.Deck with{Revision=2},ClientJourneyId=Guid.NewGuid().ToString(),SupersedesJourneyId=source});Assert.Equal(JobState.Superseded,Assert.Single(s.Jobs(p.PairingId),x=>x.JobId==old.JobId).State);Assert.Equal(JobState.Queued,amended.State);}
    [Fact] public void AwaitingSaveRejectsSuccessorAndPreservesOriginalEvidence(){
        using var s=new BridgeStore(Temp());var p=Pair(s);var d=Deck() with{Name="First",Revision=1};var link=new LinkRequest(Guid.NewGuid().ToString(),d.DeckId,"p",2,1,"other");var snap=WritableSnapshot(2,"other");s.Link(p.PairingId,link,snap);
        var first=s.Queue(p.PairingId,new("p",2,"other",d,"other",link.LinkId,1));
        s.ExecuteOneNormalJob(new FixedReader(snap),Planner,(request,_)=>new WriteResult(JobState.AppliedAwaitingGameSave,new(new("Old",snap.Arsenals[1].SkillIds,2),new(request.Deck.Name,request.Deck.SkillIds,2))));
        var applied=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(JobState.AppliedAwaitingGameSave,applied.State);Assert.Equal("Old",applied.Changes!.Before.Name);
        var expected=Planner.TargetFingerprint(2,"First",2,d.SkillIds);
        Assert.Throws<BridgeException>(()=>s.Queue(p.PairingId,new("p",2,expected,d with{Name="Second",Revision=2},expected,link.LinkId,1,Guid.NewGuid().ToString())));
        Assert.Equal(first.JobId,Assert.Single(s.Jobs(p.PairingId)).JobId);
    }
    [Fact] public void CancelBeforeArrivalTombstoneSurvivesRestart(){
        var path=Temp();string pairing;QueueRequest request;
        using(var store=new BridgeStore(path)){var pair=Pair(store);pairing=pair.PairingId;request=Link(store,pair) with{ClientJourneyId=Guid.NewGuid().ToString()};store.CancelJourney(pairing,request.ClientJourneyId!);}
        using(var store=new BridgeStore(path)){Assert.Throws<BridgeException>(()=>store.Queue(pairing,request));Assert.Empty(store.Jobs(pairing));}
    }
    [Fact] public void OwnershipTransferRetryIsIdempotent(){
        using var store=new BridgeStore(Temp());var pair=Pair(store);var old=Link(store,pair);
        var request=new LinkRequest(Guid.NewGuid().ToString(),Guid.NewGuid().ToString(),old.ProfileKey,old.TargetSlot,1,old.ConfirmedFingerprint,ReplacesLinkId:old.LinkId,ReplacesLinkGeneration:old.LinkGeneration);
        var first=store.Link(pair.PairingId,request,Snapshot(targetCopies:0));var retry=store.Link(pair.PairingId,request,Snapshot(targetCopies:0));Assert.Equal(first,retry);Assert.Single(store.Links(pair.PairingId));
    }
    [Fact] public void ReorderedDiskSavePromotesHistoricalRecoveryAndRebasesLink(){using var s=new BridgeStore(Temp());var p=Pair(s);var d=Deck() with{Name="Saved",Revision=1,SkillIds=new[]{"001","002"}.Concat(Enumerable.Repeat("000",28)).ToArray()};var link=new LinkRequest(Guid.NewGuid().ToString(),d.DeckId,"p",2,1,"other");var before=WritableSnapshot(2,"other");s.Link(p.PairingId,link,before);s.Queue(p.PairingId,new("p",2,"other",d,"other",link.LinkId,1,Guid.NewGuid().ToString()));s.ExecuteOneNormalJob(new FixedReader(before),Planner,(_,_)=>new(JobState.RecoveryRequired,Reason:"Phantom Dust saved, but Arsenal changed during save."));var reordered=d.SkillIds.Reverse().ToArray();var observed=before with{Arsenals=before.Arsenals.Select(x=>x.Slot==2?x with{Name=d.Name,SkillIds=reordered,Fingerprint="observed-after"}:x).ToArray()};s.ExecuteOneNormalJob(new FixedReader(observed),Planner,(_,_)=>throw new Exception("must not write again"));var job=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(JobState.Completed,job.State);Assert.Equal("Synced",job.Phase);Assert.Equal("observed-after",Assert.Single(s.Links(p.PairingId)).ExpectedFingerprint);}
    [Fact] public void ReorderedRecoveryRequiresExactCaseCapacity(){using var s=new BridgeStore(Temp());var p=Pair(s);var d=Deck() with{Name="Saved",SkillIds=new[]{"001","002"}.Concat(Enumerable.Repeat("000",28)).ToArray()};var link=new LinkRequest(Guid.NewGuid().ToString(),d.DeckId,"p",2,1,"other");var before=WritableSnapshot(2,"other");s.Link(p.PairingId,link,before);s.Queue(p.PairingId,new("p",2,"other",d,"other",link.LinkId,1));s.ExecuteOneNormalJob(new FixedReader(before),Planner,(_,_)=>new(JobState.RecoveryRequired,Reason:"Phantom Dust saved, but Arsenal changed during save."));var observed=before with{Arsenals=before.Arsenals.Select(x=>x.Slot==2?x with{Name=d.Name,CaseCapacity=3,SkillIds=d.SkillIds.Reverse().ToArray(),Fingerprint="larger-case"}:x).ToArray()};s.ExecuteOneNormalJob(new FixedReader(observed),Planner,(_,_)=>throw new Exception("must not write recovery"));Assert.Equal(JobState.RecoveryRequired,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void RecoveryRejectsLinkRenewal(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);s.Queue(p.PairingId,r);s.ExecuteOneNormalJob(new FixedReader(Snapshot() with{WriteSupported=true}),Planner,(_,_)=>new(JobState.RecoveryRequired,Reason:"uncertain save"));Assert.Throws<BridgeException>(()=>s.Link(p.PairingId,new(r.LinkId,r.Deck.DeckId,r.ProfileKey,r.TargetSlot,r.LinkGeneration+1,r.ConfirmedFingerprint),Snapshot()));Assert.Equal(JobState.RecoveryRequired,Assert.Single(s.Jobs(p.PairingId)).State);}
    [Fact] public void ObservedNativeDiskCommitCompletesAndAdvancesLink(){using var s=new BridgeStore(Temp());var p=Pair(s);var d=Deck() with{Name="Saved",Revision=1};var link=new LinkRequest(Guid.NewGuid().ToString(),d.DeckId,"p",2,1,"other");var snap=WritableSnapshot(2,"other");s.Link(p.PairingId,link,snap);s.Queue(p.PairingId,new("p",2,"other",d,"other",link.LinkId,1));s.ExecuteOneNormalJob(new FixedReader(snap),Planner,(request,_)=>new WriteResult(JobState.Completed,new(new("Old",snap.Arsenals[1].SkillIds,2),new(request.Deck.Name,request.Deck.SkillIds,2)),"Phantom Dust committed the profile save."));Assert.Equal(JobState.Completed,Assert.Single(s.Jobs(p.PairingId)).State);Assert.Equal(Planner.TargetFingerprint(2,d.Name,2,d.SkillIds),Assert.Single(s.Links(p.PairingId)).ExpectedFingerprint);}
    [Fact] public void RecoveryRequiresExplicitReviewOfCurrentTarget(){using var s=new BridgeStore(Temp());var p=Pair(s);var r=Link(s,p);var queued=s.Queue(p.PairingId,r);var snap=Snapshot() with{WriteSupported=true};s.ExecuteOneNormalJob(new FixedReader(snap),Planner,(_,_)=>new(JobState.RecoveryRequired,Reason:"uncertain"));var recovery=Assert.Single(s.Jobs(p.PairingId));Assert.Equal(JobState.RecoveryRequired,recovery.State);Assert.Throws<BridgeException>(()=>s.ResolveRecovery(p.PairingId,recovery.JobId,new("p",1,"stale"),snap));var resolved=s.ResolveRecovery(p.PairingId,recovery.JobId,new("p",1,"target"),snap);Assert.Equal(JobState.Superseded,resolved.State);}
    private sealed class FixedReader(Snapshot snapshot):IPhantomDustProfileReader { public Snapshot Read()=>snapshot; }
    private static Snapshot WritableSnapshot(int slot,string fingerprint)=>new("p","snapshot",Wire.Now,true,true,true,true,false,[new(1,"Unrelated",2,Enumerable.Repeat("000",30).ToArray(),"other"),new(slot,"Old",2,Enumerable.Repeat("000",30).ToArray(),fingerprint)],new Dictionary<string,int>{{"001",9},{"002",9}},GameProfileDisplayName:"Profile");
}

